#!/usr/bin/env python3
"""Generate Drive_to_BigQuery.ipynb with the pipeline embedded.

The notebook has to run in Colab with no clone step and no credentials to
paste, so it carries its own copy of the modules. Generating it from the real
sources keeps that copy from drifting -- re-run this after touching any module.

    python build_notebook.py
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
MODULES = ["classify.py", "drive.py", "parse.py", "chunk.py", "vectorize.py",
           "bq.py", "pipeline.py"]
NOTEBOOK = HERE / "Drive_to_BigQuery.ipynb"

PROJECT = "pelagic-gist-505800-b9"


def markdown(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _src(lines),
    }


def _src(lines) -> list[str]:
    """nbformat wants a list of lines, each keeping its trailing newline."""
    text = "\n".join(lines)
    out = text.splitlines(keepends=True)
    if out and not out[-1].endswith("\n"):
        return out
    return out


def bootstrap_cell() -> dict:
    """A cell that writes each module to disk from an embedded copy."""
    lines = [
        "# The pipeline modules, embedded so this notebook needs no clone step.",
        "# Generated by build_notebook.py -- edit the .py files, not this cell.",
        "import pathlib, textwrap",
        "",
        "MODULES = {}",
    ]
    for name in MODULES:
        source = (HERE / name).read_text()
        # A unique heredoc marker avoids collisions with the code's own quotes.
        marker = f"__{name.replace('.', '_').upper()}__"
        lines.append("")
        lines.append(f"MODULES[{name!r}] = r'''{marker}")
        lines.append(source.rstrip("\n"))
        lines.append(f"{marker}'''")
    lines += [
        "",
        "for _name, _text in MODULES.items():",
        "    # Strip the heredoc markers off both ends.",
        "    _body = _text.split('\\n', 1)[1].rsplit('\\n', 1)[0]",
        "    pathlib.Path(_name).write_text(_body)",
        "",
        "print('wrote:', ', '.join(MODULES))",
    ]
    return code(*lines)


def build() -> None:
    cells = [
        markdown(
            "# Drive → BigQuery",
            "",
            f"Loads your Google Drive into BigQuery project `{PROJECT}`, then embeds it for"
            " semantic search. Four datasets:",
            "",
            "| Dataset | Contents |",
            "|---|---|",
            "| `drive_raw.file_manifest` | One row per file in Drive — the census. Every file"
            " appears whether it loaded, failed, or was excluded. Nothing disappears silently. |",
            "| `drive_tables.<name>` | One table per *family* of tabular files. |",
            "| `drive_documents` | Extracted text from PDF, Word, PowerPoint, txt, md — plus"
            " `document_chunks`, the passages that get embedded. |",
            "| `drive_vectors.embeddings` | One vector table over documents, spreadsheet rows"
            " **and** filenames, with a `search()` function. |",
            "",
            "**Why the grouping matters.** A Takeout/Fitbit export is thousands of files that"
            " are really a few dozen tables sharded by day:",
            "",
            "```",
            "heart_rate_2026-03-23.csv",
            "heart_rate_2026-03-24.csv",
            "heart_rate_2026-04-05.csv",
            "```",
            "",
            "Loading one table per file gives you 1000+ useless single-day tables. These are"
            " grouped into one table, with the date kept as a `_src_date` column."
            " On the first 100 CSVs in this Drive: **100 files → 28 tables.**",
            "",
            "**Why Colab.** Your Drive mounts as ordinary files, so there is no API"
            " pagination and no download quota, and BigQuery authenticates as *you* —"
            " no service account, no JSON key, nothing to paste.",
            "",
            "Run the cells in order. Nothing is written to BigQuery until step 5, and step 4"
            " shows you the full plan first.",
        ),
        markdown("## 1. Install dependencies"),
        code(
            "%pip install --quiet google-cloud-bigquery google-api-python-client \\",
            "    pandas pyarrow openpyxl xlrd pypdf python-docx python-pptx",
            "print('dependencies installed')",
        ),
        markdown("## 2. Write out the pipeline"),
        bootstrap_cell(),
        markdown(
            "## 3. Mount Drive and authenticate",
            "",
            "Two consent prompts: one to mount Drive, one for Google Cloud. Both are your"
            " own account — nothing is shared with anyone.",
        ),
        code(
            "from google.colab import auth, drive",
            "",
            "drive.mount('/content/drive')",
            "auth.authenticate_user()",
            "print('Drive mounted and Google Cloud authenticated')",
        ),
        markdown(
            "## 4. Preview the plan",
            "",
            "Walks the mount and prints exactly what it would build. **No BigQuery writes.**",
            "",
            "`--skip-health` excludes wearable telemetry — the per-day Fitbit-style exports"
            " (`heart_rate_*`, `body_temperature_*`, `micro_motion_*`, steps, calories, SpO2"
            " and so on). These are millions of rows of near-zero information per row and"
            " nothing worth embedding.",
            "",
            "**What `--skip-health` does *not* exclude:** your clinical notes, medical PDFs,"
            " and anything under `Medical Notes`. Those are documents, not telemetry, and they"
            " are kept and vectored. If you want those out too, add"
            " `--exclude-path 'Medical Notes'`.",
            "",
            "Excluded files are still recorded in `drive_raw.file_manifest` as `excluded`, so"
            " the census stays a complete picture of the Drive.",
        ),
        code(
            f"PROJECT = {PROJECT!r}",
            "ROOT = '/content/drive/MyDrive'",
            "LOCATION = 'US'",
            "",
            "!python pipeline.py plan --project $PROJECT --local-root \"$ROOT\" \\",
            "    --skip-health --vectorize",
        ),
        markdown(
            "## 5. Load",
            "",
            "Review the table list above first. This is the step that writes to BigQuery.",
            "",
            "Safe to re-run: file ids already marked loaded in the manifest are skipped, so"
            " an interrupted run resumes instead of duplicating rows. A file that fails is"
            " recorded in the manifest and does not abort the run.",
            "",
            "Add `--dry-run` to log every operation without executing it. Add `--replace` to"
            " truncate the tables first rather than appending. Drop `--skip-health` to bring"
            " the telemetry in as well.",
        ),
        code(
            "!python pipeline.py load --project $PROJECT --local-root \"$ROOT\" \\",
            "    --location $LOCATION --skip-health --from-cache",
        ),
        markdown(
            "## 6. Connect BigQuery to Vertex AI",
            "",
            "Embeddings are generated **inside** BigQuery by `ML.GENERATE_EMBEDDING`, so the"
            " text never leaves BigQuery and there is no client-side embedding loop.",
            "",
            "That needs a one-time CLOUD_RESOURCE connection, and the connection's own service"
            " account needs Vertex access. This cell creates the connection, reads back its"
            " service account, and grants it `roles/aiplatform.user`.",
            "",
            "It also enables the Vertex AI API if it is not already on. Both steps need you to"
            " be an owner/editor on the project.",
        ),
        code(
            "import json, subprocess",
            "",
            "CONNECTION = 'drive_vertex'",
            "",
            "!gcloud services enable aiplatform.googleapis.com --project $PROJECT --quiet",
            "",
            "# Create the connection (harmless if it already exists).",
            "!bq mk --connection --location=$LOCATION --project_id=$PROJECT \\",
            "    --connection_type=CLOUD_RESOURCE $CONNECTION 2>/dev/null || true",
            "",
            "info = subprocess.run(",
            "    ['bq', 'show', '--format=json', '--connection',",
            "     f'{PROJECT}.{LOCATION}.{CONNECTION}'],",
            "    capture_output=True, text=True)",
            "assert info.returncode == 0, info.stderr",
            "SA = json.loads(info.stdout)['cloudResource']['serviceAccountId']",
            "print('connection service account:', SA)",
            "",
            "# Let that service account call Vertex.",
            "!gcloud projects add-iam-policy-binding $PROJECT \\",
            "    --member=serviceAccount:$SA --role=roles/aiplatform.user --quiet",
            "print('granted roles/aiplatform.user')",
        ),
        markdown(
            "## 7. Vectorize",
            "",
            "Embeds three things into one searchable table, `drive_vectors.embeddings`:",
            "",
            "| Source | What gets embedded |",
            "|---|---|",
            "| `document_chunk` | Every PDF/Word/slide/text document, split into ~2000-char"
            " overlapping passages so a hit points at a findable location. |",
            "| `file_metadata` | Name, folder, type and date of every image, video and binary."
            " A photo has no extractable text, but *\"that scan from the hospital\"* still"
            " needs to be findable. |",
            "| `table_row` | Rows of the tables you name in `--vectorize-tables` — for"
            " spreadsheets of names, dates and notes. |",
            "",
            "One index over all of it means one query searches the whole Drive.",
            "",
            "The IAM grant above can take a minute to propagate. If this fails with a"
            " permission error, wait and re-run — it is idempotent and resumes from the queue.",
        ),
        code(
            "# Name the descriptive tables whose individual rows are worth searching.",
            "# Check the step-4 output for the real table names and edit this list.",
            "VECTOR_TABLES = 'pgy_1 pgy_2 pgy_3 ops_decertification_list_4_19_23'",
            "",
            "!python pipeline.py vectorize --project $PROJECT --location $LOCATION \\",
            "    --vectorize-tables $VECTOR_TABLES",
        ),
        markdown(
            "## 8. Check the result",
            "",
            "Row counts per table, then anything that did not load and why.",
        ),
        code(
            "from google.cloud import bigquery",
            "client = bigquery.Client(project=PROJECT)",
            "",
            "print('--- rows per table ---')",
            "tables = list(client.list_tables(f'{PROJECT}.drive_tables'))",
            "for table in sorted(tables, key=lambda t: t.table_id):",
            "    meta = client.get_table(table.reference)",
            "    print(f'{table.table_id:<44} {meta.num_rows:>12,} rows'",
            "          f'  {len(meta.schema):>3} cols')",
            "",
            "print()",
            "print('--- ingest status ---')",
            "for row in client.query(f'''",
            "    SELECT ingest_status, COUNT(*) AS files, SUM(row_count) AS rows",
            "    FROM `{PROJECT}.drive_raw.file_manifest`",
            "    GROUP BY ingest_status ORDER BY files DESC",
            "'''):",
            "    print(f'{row.ingest_status:<16} {row.files:>6} files  {row.rows or 0:>12,} rows')",
        ),
        markdown(
            "### Anything that failed",
            "",
            "Empty result means everything loaded.",
        ),
        code(
            "for row in client.query(f'''",
            "    SELECT name, kind, fmt, size_bytes, ingest_error",
            "    FROM `{PROJECT}.drive_raw.file_manifest`",
            "    WHERE ingest_status = 'failed'",
            "    ORDER BY size_bytes DESC LIMIT 50",
            "'''):",
            "    print(f'{row.name[:52]:<54} {row.ingest_error}')",
        ),
        markdown(
            "### What got vectored",
        ),
        code(
            "for row in client.query(f'''",
            "    SELECT source_kind, COUNT(*) AS vectors,",
            "           COUNT(DISTINCT file_id) AS files,",
            "           ANY_VALUE(ARRAY_LENGTH(embedding)) AS dims",
            "    FROM `{PROJECT}.drive_vectors.embeddings`",
            "    GROUP BY source_kind ORDER BY vectors DESC",
            "'''):",
            "    print(f'{row.source_kind:<18} {row.vectors:>8,} vectors  '",
            "          f'{row.files:>6,} files  {row.dims} dims')",
            "",
            "# Anything still queued failed to embed and can be retried.",
            "left = list(client.query(f'''",
            "    SELECT COUNT(*) AS n FROM `{PROJECT}.drive_vectors.embed_queue`",
            "'''))[0].n",
            "print(f'\\nstill queued: {left:,}' if left else '\\nqueue empty — all embedded')",
        ),
        markdown(
            "## 9. Semantic search",
            "",
            "The payoff. Ask in plain language; it searches documents, spreadsheet rows and"
            " filenames at once. `distance` is cosine — lower is closer.",
        ),
        code(
            "QUESTION = 'academic probation appeal deadline'",
            "",
            "client.query(f'''",
            "    SELECT name, source_kind, ROUND(distance, 4) AS distance,",
            "           SUBSTR(content, 1, 300) AS excerpt",
            "    FROM `{PROJECT}.drive_vectors.search`(@q, 10)",
            "    ORDER BY distance",
            "''', job_config=bigquery.QueryJobConfig(",
            "    query_parameters=[bigquery.ScalarQueryParameter('q', 'STRING', QUESTION)]",
            ")).to_dataframe()",
        ),
        markdown(
            "Try others — `'residency evaluation concerns'`, `'decertification'`,"
            " `'what did the clinic note say about sleep'`. Because filenames are vectored"
            " too, searches like `'hospital scan photo'` surface images that contain no text"
            " at all.",
        ),
        markdown(
            "---",
            "",
            "**Note on native Google files.** Sheets, Docs and Slides are not real files on"
            " the mount — Drive represents them as small stub files with no data. The"
            " pipeline recovers their file id from the stub and exports them through the"
            " Drive API. If Colab's credentials lack the Drive scope they are recorded as"
            " `failed` in the manifest with a clear reason, and everything else still loads."
            " Uploaded `.xlsx` files are real files and are unaffected.",
        ),
    ]

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 0,
        "metadata": {
            "colab": {"provenance": [], "toc_visible": True},
            "kernelspec": {"name": "python3", "display_name": "Python 3"},
            "language_info": {"name": "python"},
        },
        "cells": cells,
    }
    NOTEBOOK.write_text(json.dumps(notebook, indent=1))
    size = NOTEBOOK.stat().st_size
    print(f"wrote {NOTEBOOK.name} ({len(cells)} cells, {size:,} bytes)")


if __name__ == "__main__":
    build()
