#!/usr/bin/env python3
"""Generate Drive_to_BigQuery.ipynb with the pipeline embedded.

The notebook has to run in Colab with no clone step and no credentials to
paste, so it carries its own copy of the modules. Generating it from the real
sources keeps that copy from drifting -- re-run this after touching any module.

    python build_notebook.py
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
MODULES = ["classify.py", "drive.py", "parse.py", "bq.py", "pipeline.py"]
NOTEBOOK = HERE / "Drive_to_BigQuery.ipynb"

PROJECT = "pelagic-gist-505800-b9"


def markdown(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _src(lines),
    }


def _src(lines) -> list[str]:
    """nbformat wants a list of lines, each keeping its trailing newline."""
    text = "\n".join(lines)
    out = text.splitlines(keepends=True)
    if out and not out[-1].endswith("\n"):
        return out
    return out


def bootstrap_cell() -> dict:
    """A cell that writes each module to disk from an embedded copy."""
    lines = [
        "# The pipeline modules, embedded so this notebook needs no clone step.",
        "# Generated by build_notebook.py -- edit the .py files, not this cell.",
        "import pathlib, textwrap",
        "",
        "MODULES = {}",
    ]
    for name in MODULES:
        source = (HERE / name).read_text()
        # A unique heredoc marker avoids collisions with the code's own quotes.
        marker = f"__{name.replace('.', '_').upper()}__"
        lines.append("")
        lines.append(f"MODULES[{name!r}] = r'''{marker}")
        lines.append(source.rstrip("\n"))
        lines.append(f"{marker}'''")
    lines += [
        "",
        "for _name, _text in MODULES.items():",
        "    # Strip the heredoc markers off both ends.",
        "    _body = _text.split('\\n', 1)[1].rsplit('\\n', 1)[0]",
        "    pathlib.Path(_name).write_text(_body)",
        "",
        "print('wrote:', ', '.join(MODULES))",
    ]
    return code(*lines)


def build() -> None:
    cells = [
        markdown(
            "# Drive → BigQuery",
            "",
            f"Loads your Google Drive into BigQuery project `{PROJECT}` as three datasets:",
            "",
            "| Dataset | Contents |",
            "|---|---|",
            "| `drive_raw.file_manifest` | One row per file in Drive — the census. Every file"
            " appears whether it loaded or not, with its error. Nothing disappears silently. |",
            "| `drive_tables.<name>` | One table per *family* of tabular files. |",
            "| `drive_documents.documents` | Extracted text from PDF, Word, PowerPoint, txt, md. |",
            "",
            "**Why this exists.** A Takeout/Fitbit export is thousands of files that are"
            " really a few dozen tables sharded by day:",
            "",
            "```",
            "heart_rate_2026-03-23.csv",
            "heart_rate_2026-03-24.csv",
            "heart_rate_2026-04-05.csv",
            "```",
            "",
            "Loading one table per file gives you 1000+ useless single-day tables. These are"
            " grouped into one `heart_rate` table, with the date kept as a `_src_date` column."
            " On the first 100 CSVs in this Drive: **100 files → 28 tables.**",
            "",
            "**Why Colab.** Your Drive mounts as ordinary files, so there is no API"
            " pagination and no download quota, and BigQuery authenticates as *you* —"
            " no service account, no JSON key, nothing to paste.",
            "",
            "Run the cells in order. Nothing is written to BigQuery until step 5.",
        ),
        markdown("## 1. Install dependencies"),
        code(
            "%pip install --quiet google-cloud-bigquery google-api-python-client \\",
            "    pandas pyarrow openpyxl xlrd pypdf python-docx python-pptx",
            "print('dependencies installed')",
        ),
        markdown("## 2. Write out the pipeline"),
        bootstrap_cell(),
        markdown(
            "## 3. Mount Drive and authenticate",
            "",
            "Two consent prompts: one to mount Drive, one for Google Cloud. Both are your"
            " own account — nothing is shared with anyone.",
        ),
        code(
            "from google.colab import auth, drive",
            "",
            "drive.mount('/content/drive')",
            "auth.authenticate_user()",
            "print('Drive mounted and Google Cloud authenticated')",
        ),
        markdown(
            "## 4. Preview the plan",
            "",
            "Walks the mount and prints the tables it would build. **No BigQuery writes.**",
            "",
            "`ROOT` is the folder to ingest. `/content/drive/MyDrive` is your whole Drive;"
            " narrow it to a subfolder to start smaller — e.g."
            " `/content/drive/MyDrive/D:/Takeout` for just the health export.",
        ),
        code(
            f"PROJECT = {PROJECT!r}",
            "ROOT = '/content/drive/MyDrive'",
            "LOCATION = 'US'",
            "",
            "!python pipeline.py plan --project $PROJECT --local-root \"$ROOT\"",
        ),
        markdown(
            "## 5. Load",
            "",
            "Review the table list above first. This is the step that writes to BigQuery.",
            "",
            "Safe to re-run: file ids already marked loaded in the manifest are skipped, so"
            " an interrupted run resumes instead of duplicating rows. A file that fails is"
            " recorded in the manifest and does not abort the run.",
            "",
            "Add `--dry-run` to log every operation without executing it. Add `--replace` to"
            " truncate the tables first rather than appending.",
        ),
        code(
            "!python pipeline.py load --project $PROJECT --local-root \"$ROOT\" \\",
            "    --location $LOCATION --from-cache",
        ),
        markdown(
            "## 6. Check the result",
            "",
            "Row counts per table, then anything that did not load and why.",
        ),
        code(
            "from google.cloud import bigquery",
            "client = bigquery.Client(project=PROJECT)",
            "",
            "print('--- rows per table ---')",
            "tables = list(client.list_tables(f'{PROJECT}.drive_tables'))",
            "for table in sorted(tables, key=lambda t: t.table_id):",
            "    meta = client.get_table(table.reference)",
            "    print(f'{table.table_id:<44} {meta.num_rows:>12,} rows'",
            "          f'  {len(meta.schema):>3} cols')",
            "",
            "print()",
            "print('--- ingest status ---')",
            "for row in client.query(f'''",
            "    SELECT ingest_status, COUNT(*) AS files, SUM(row_count) AS rows",
            "    FROM `{PROJECT}.drive_raw.file_manifest`",
            "    GROUP BY ingest_status ORDER BY files DESC",
            "'''):",
            "    print(f'{row.ingest_status:<16} {row.files:>6} files  {row.rows or 0:>12,} rows')",
        ),
        markdown(
            "### Anything that failed",
            "",
            "Empty result means everything loaded.",
        ),
        code(
            "for row in client.query(f'''",
            "    SELECT name, kind, fmt, size_bytes, ingest_error",
            "    FROM `{PROJECT}.drive_raw.file_manifest`",
            "    WHERE ingest_status = 'failed'",
            "    ORDER BY size_bytes DESC LIMIT 50",
            "'''):",
            "    print(f'{row.name[:52]:<54} {row.ingest_error}')",
        ),
        markdown(
            "### Example query",
            "",
            "The point of the exercise — one query across the whole history that used to be"
            " hundreds of separate files.",
        ),
        code(
            "df = client.query(f'''",
            "    SELECT _src_date AS day,",
            "           COUNT(*) AS readings,",
            "           ROUND(AVG(beats_per_minute), 1) AS avg_bpm,",
            "           MIN(beats_per_minute) AS min_bpm,",
            "           MAX(beats_per_minute) AS max_bpm",
            "    FROM `{PROJECT}.drive_tables.heart_rate`",
            "    WHERE beats_per_minute IS NOT NULL",
            "    GROUP BY day ORDER BY day",
            "''').to_dataframe()",
            "df",
        ),
        markdown(
            "---",
            "",
            "**Note on native Google files.** Sheets, Docs and Slides are not real files on"
            " the mount — Drive represents them as small stub files with no data. The"
            " pipeline recovers their file id from the stub and exports them through the"
            " Drive API. If Colab's credentials lack the Drive scope they are recorded as"
            " `failed` in the manifest with a clear reason, and everything else still loads."
            " Uploaded `.xlsx` files are real files and are unaffected.",
        ),
    ]

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 0,
        "metadata": {
            "colab": {"provenance": [], "toc_visible": True},
            "kernelspec": {"name": "python3", "display_name": "Python 3"},
            "language_info": {"name": "python"},
        },
        "cells": cells,
    }
    NOTEBOOK.write_text(json.dumps(notebook, indent=1))
    size = NOTEBOOK.stat().st_size
    print(f"wrote {NOTEBOOK.name} ({len(cells)} cells, {size:,} bytes)")


if __name__ == "__main__":
    build()
