#!/usr/bin/env python3
"""Generate Drive_to_BigQuery.ipynb with the pipeline embedded.

The notebook has to run in Colab with no clone step and no credentials to
paste, so it carries its own copy of the modules. Generating it from the real
sources keeps that copy from drifting -- re-run this after touching any module.

    python build_notebook.py
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
MODULES = ["classify.py", "drive.py", "parse.py", "chunk.py", "vectorize.py",
           "graph.py", "bq.py", "pipeline.py"]
NOTEBOOK = HERE / "Drive_to_BigQuery.ipynb"

PROJECT = "pelagic-gist-505800-b9"


def markdown(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _src(lines),
    }


def _src(lines) -> list[str]:
    """nbformat wants a list of lines, each keeping its trailing newline."""
    text = "\n".join(lines)
    out = text.splitlines(keepends=True)
    if out and not out[-1].endswith("\n"):
        return out
    return out


def bootstrap_cell() -> dict:
    """A cell that writes each module to disk from an embedded copy."""
    lines = [
        "# The pipeline modules, embedded so this notebook needs no clone step.",
        "# Generated by build_notebook.py -- edit the .py files, not this cell.",
        "import pathlib, textwrap",
        "",
        "MODULES = {}",
    ]
    for name in MODULES:
        source = (HERE / name).read_text()
        # A unique heredoc marker avoids collisions with the code's own quotes.
        marker = f"__{name.replace('.', '_').upper()}__"
        lines.append("")
        lines.append(f"MODULES[{name!r}] = r'''{marker}")
        lines.append(source.rstrip("\n"))
        lines.append(f"{marker}'''")
    lines += [
        "",
        "for _name, _text in MODULES.items():",
        "    # Strip the heredoc markers off both ends.",
        "    _body = _text.split('\\n', 1)[1].rsplit('\\n', 1)[0]",
        "    pathlib.Path(_name).write_text(_body)",
        "",
        "print('wrote:', ', '.join(MODULES))",
    ]
    return code(*lines)


def build() -> None:
    cells = [
        markdown(
            "# Drive → BigQuery",
            "",
            f"Loads your Google Drive into BigQuery project `{PROJECT}`, embeds it for"
            " semantic search, then crosses it against itself so connections surface"
            " without being queried for. Five datasets:",
            "",
            "| Dataset | Contents |",
            "|---|---|",
            "| `drive_raw.file_manifest` | One row per file in Drive — the census. Every file"
            " appears whether it loaded, failed, or was excluded. Nothing disappears silently. |",
            "| `drive_tables.<name>` | One table per *family* of tabular files. |",
            "| `drive_documents` | Extracted text from PDF, Word, PowerPoint, txt, md — plus"
            " `document_chunks`, the passages that get embedded. |",
            "| `drive_vectors.embeddings` | One vector table over documents, spreadsheet rows"
            " **and** filenames, with a `search()` function. |",
            "| `drive_graph` | `cross_links` (chunk↔chunk edges), `entity_mentions`,"
            " `entities` — the corpus crossed against itself. |",
            "| `drive_insights` | Seven views over that: bridges, indirect relations,"
            " timelines, gaps, health — plus an `ask()` function. |",
            "",
            "**Why the grouping matters.** A Takeout/Fitbit export is thousands of files that"
            " are really a few dozen tables sharded by day:",
            "",
            "```",
            "heart_rate_2026-03-23.csv",
            "heart_rate_2026-03-24.csv",
            "heart_rate_2026-04-05.csv",
            "```",
            "",
            "Loading one table per file gives you 1000+ useless single-day tables. These are"
            " grouped into one table, with the date kept as a `_src_date` column."
            " On the first 100 CSVs in this Drive: **100 files → 28 tables.**",
            "",
            "**Why Colab.** Your Drive mounts as ordinary files, so there is no API"
            " pagination and no download quota, and BigQuery authenticates as *you* —"
            " no service account, no JSON key, nothing to paste.",
            "",
            "Run the cells in order. Nothing is written to BigQuery until step 5, and step 4"
            " shows you the full plan first.",
        ),
        markdown("## 1. Install dependencies"),
        code(
            "%pip install --quiet google-cloud-bigquery google-api-python-client \\",
            "    pandas pyarrow openpyxl xlrd pypdf python-docx python-pptx",
            "print('dependencies installed')",
        ),
        markdown("## 2. Write out the pipeline"),
        bootstrap_cell(),
        markdown(
            "## 3. Mount Drive and authenticate",
            "",
            "Two consent prompts: one to mount Drive, one for Google Cloud. Both are your"
            " own account — nothing is shared with anyone.",
        ),
        code(
            "from google.colab import auth, drive",
            "",
            "drive.mount('/content/drive')",
            "auth.authenticate_user()",
            "print('Drive mounted and Google Cloud authenticated')",
        ),
        markdown(
            "## 4. Preview the plan",
            "",
            "Walks the mount and prints exactly what it would build. **No BigQuery writes.**",
            "",
            "`--skip-health` excludes wearable telemetry — the per-day Fitbit-style exports"
            " (`heart_rate_*`, `body_temperature_*`, `micro_motion_*`, steps, calories, SpO2"
            " and so on). These are millions of rows of near-zero information per row and"
            " nothing worth embedding.",
            "",
            "**What `--skip-health` does *not* exclude:** your clinical notes, medical PDFs,"
            " and anything under `Medical Notes`. Those are documents, not telemetry, and they"
            " are kept and vectored. If you want those out too, add"
            " `--exclude-path 'Medical Notes'`.",
            "",
            "Excluded files are still recorded in `drive_raw.file_manifest` as `excluded`, so"
            " the census stays a complete picture of the Drive.",
        ),
        code(
            f"PROJECT = {PROJECT!r}",
            "ROOT = '/content/drive/MyDrive'",
            "LOCATION = 'US'",
            "",
            "!python pipeline.py plan --project $PROJECT --local-root \"$ROOT\" \\",
            "    --skip-health --vectorize",
        ),
        markdown(
            "## 5. Load",
            "",
            "Review the table list above first. This is the step that writes to BigQuery.",
            "",
            "Safe to re-run: file ids already marked loaded in the manifest are skipped, so"
            " an interrupted run resumes instead of duplicating rows. A file that fails is"
            " recorded in the manifest and does not abort the run.",
            "",
            "Add `--dry-run` to log every operation without executing it. Add `--replace` to"
            " truncate the tables first rather than appending. Drop `--skip-health` to bring"
            " the telemetry in as well.",
        ),
        code(
            "!python pipeline.py load --project $PROJECT --local-root \"$ROOT\" \\",
            "    --location $LOCATION --skip-health --from-cache",
        ),
        markdown(
            "## 6. Connect BigQuery to Vertex AI",
            "",
            "Embeddings are generated **inside** BigQuery by `ML.GENERATE_EMBEDDING`, so the"
            " text never leaves BigQuery and there is no client-side embedding loop.",
            "",
            "That needs a one-time CLOUD_RESOURCE connection, and the connection's own service"
            " account needs Vertex access. This cell creates the connection, reads back its"
            " service account, and grants it `roles/aiplatform.user`.",
            "",
            "It also enables the Vertex AI API if it is not already on. Both steps need you to"
            " be an owner/editor on the project.",
        ),
        code(
            "import json, subprocess",
            "",
            "CONNECTION = 'drive_vertex'",
            "",
            "!gcloud services enable aiplatform.googleapis.com --project $PROJECT --quiet",
            "",
            "# Create the connection (harmless if it already exists).",
            "!bq mk --connection --location=$LOCATION --project_id=$PROJECT \\",
            "    --connection_type=CLOUD_RESOURCE $CONNECTION 2>/dev/null || true",
            "",
            "info = subprocess.run(",
            "    ['bq', 'show', '--format=json', '--connection',",
            "     f'{PROJECT}.{LOCATION}.{CONNECTION}'],",
            "    capture_output=True, text=True)",
            "assert info.returncode == 0, info.stderr",
            "SA = json.loads(info.stdout)['cloudResource']['serviceAccountId']",
            "print('connection service account:', SA)",
            "",
            "# Let that service account call Vertex.",
            "!gcloud projects add-iam-policy-binding $PROJECT \\",
            "    --member=serviceAccount:$SA --role=roles/aiplatform.user --quiet",
            "print('granted roles/aiplatform.user')",
        ),
        markdown(
            "## 7. Vectorize",
            "",
            "Embeds three things into one searchable table, `drive_vectors.embeddings`:",
            "",
            "| Source | What gets embedded |",
            "|---|---|",
            "| `document_chunk` | Every PDF/Word/slide/text document, split into ~2000-char"
            " overlapping passages so a hit points at a findable location. |",
            "| `file_metadata` | Name, folder, type and date of every image, video and binary."
            " A photo has no extractable text, but *\"that scan from the hospital\"* still"
            " needs to be findable. |",
            "| `table_row` | Rows of the tables you name in `--vectorize-tables` — for"
            " spreadsheets of names, dates and notes. |",
            "",
            "One index over all of it means one query searches the whole Drive.",
            "",
            "The IAM grant above can take a minute to propagate. If this fails with a"
            " permission error, wait and re-run — it is idempotent and resumes from the queue.",
        ),
        code(
            "# Name the descriptive tables whose individual rows are worth searching.",
            "# Check the step-4 output for the real table names and edit this list.",
            "VECTOR_TABLES = 'pgy_1 pgy_2 pgy_3 ops_decertification_list_4_19_23'",
            "",
            "!python pipeline.py vectorize --project $PROJECT --location $LOCATION \\",
            "    --vectorize-tables $VECTOR_TABLES",
        ),
        markdown(
            "## 8. Check the result",
            "",
            "Row counts per table, then anything that did not load and why.",
        ),
        code(
            "from google.cloud import bigquery",
            "client = bigquery.Client(project=PROJECT)",
            "",
            "print('--- rows per table ---')",
            "tables = list(client.list_tables(f'{PROJECT}.drive_tables'))",
            "for table in sorted(tables, key=lambda t: t.table_id):",
            "    meta = client.get_table(table.reference)",
            "    print(f'{table.table_id:<44} {meta.num_rows:>12,} rows'",
            "          f'  {len(meta.schema):>3} cols')",
            "",
            "print()",
            "print('--- ingest status ---')",
            "for row in client.query(f'''",
            "    SELECT ingest_status, COUNT(*) AS files, SUM(row_count) AS rows",
            "    FROM `{PROJECT}.drive_raw.file_manifest`",
            "    GROUP BY ingest_status ORDER BY files DESC",
            "'''):",
            "    print(f'{row.ingest_status:<16} {row.files:>6} files  {row.rows or 0:>12,} rows')",
        ),
        markdown(
            "### Anything that failed",
            "",
            "Empty result means everything loaded.",
        ),
        code(
            "for row in client.query(f'''",
            "    SELECT name, kind, fmt, size_bytes, ingest_error",
            "    FROM `{PROJECT}.drive_raw.file_manifest`",
            "    WHERE ingest_status = 'failed'",
            "    ORDER BY size_bytes DESC LIMIT 50",
            "'''):",
            "    print(f'{row.name[:52]:<54} {row.ingest_error}')",
        ),
        markdown(
            "### What got vectored",
        ),
        code(
            "for row in client.query(f'''",
            "    SELECT source_kind, COUNT(*) AS vectors,",
            "           COUNT(DISTINCT file_id) AS files,",
            "           ANY_VALUE(ARRAY_LENGTH(embedding)) AS dims",
            "    FROM `{PROJECT}.drive_vectors.embeddings`",
            "    GROUP BY source_kind ORDER BY vectors DESC",
            "'''):",
            "    print(f'{row.source_kind:<18} {row.vectors:>8,} vectors  '",
            "          f'{row.files:>6,} files  {row.dims} dims')",
            "",
            "# Anything still queued failed to embed and can be retried.",
            "left = list(client.query(f'''",
            "    SELECT COUNT(*) AS n FROM `{PROJECT}.drive_vectors.embed_queue`",
            "'''))[0].n",
            "print(f'\\nstill queued: {left:,}' if left else '\\nqueue empty — all embedded')",
        ),
        markdown(
            "## 9. Semantic search",
            "",
            "The payoff. Ask in plain language; it searches documents, spreadsheet rows and"
            " filenames at once. `distance` is cosine — lower is closer.",
        ),
        code(
            "QUESTION = 'academic probation appeal deadline'",
            "",
            "client.query(f'''",
            "    SELECT name, source_kind, ROUND(distance, 4) AS distance,",
            "           SUBSTR(content, 1, 300) AS excerpt",
            "    FROM `{PROJECT}.drive_vectors.search`(@q, 10)",
            "    ORDER BY distance",
            "''', job_config=bigquery.QueryJobConfig(",
            "    query_parameters=[bigquery.ScalarQueryParameter('q', 'STRING', QUESTION)]",
            ")).to_dataframe()",
        ),
        markdown(
            "Try others — `'residency evaluation concerns'`, `'decertification'`,"
            " `'what did the clinic note say about sleep'`. Because filenames are vectored"
            " too, searches like `'hospital scan photo'` surface images that contain no text"
            " at all.",
        ),
        markdown(
            "## 10. Cross the data against itself",
            "",
            "Search only answers what you thought to ask. This step makes the corpus"
            " surface connections nobody queried for, in two passes:",
            "",
            "**Pass 1 — crossing.** Every chunk is searched against every other chunk, and"
            " nearest neighbours *in different files* are recorded as edges. A passage in a"
            " probation letter and a row in a residency evaluation that discuss the same"
            " thing become an explicit link, with no query typed by anyone.",
            "",
            "**Pass 2 — crossing the crossings.** Entities are extracted from each chunk,"
            " then pushed *through* those edges. Two people who never appear in the same"
            " file, but who are each central to files that link to one another, get"
            " surfaced as related. That relationship exists in no single document — only"
            " in the geometry between them.",
            "",
            "Both passes are resumable and skip work already done, so re-running after"
            " adding files only processes the new material.",
        ),
        code(
            "# Pass 1: edges between chunks in different files.",
            "!python pipeline.py crosslink --project $PROJECT --location $LOCATION",
        ),
        code(
            "# Pass 2: entities, then the derived views. --insight-feed additionally has",
            "# Gemini write up the strongest bridges in plain language (costs tokens).",
            "!python pipeline.py entities --project $PROJECT --location $LOCATION",
            "!python pipeline.py insights --project $PROJECT --location $LOCATION \\",
            "    --insight-feed",
        ),
        markdown(
            "## 11. The insights",
            "",
            "Seven views in `drive_insights`. Each cell below is one question you could not"
            " ask of the raw Drive.",
        ),
        markdown(
            "### Where two parts of your Drive meet",
            "",
            "File pairs joined by many semantic links. `crosses_folder` marks pairs from"
            " *different* top-level folders — a link that crosses how you organised things"
            " is usually the interesting one.",
        ),
        code(
            "client.query(f'''",
            "    SELECT a_name, b_name, link_count,",
            "           ROUND(closest_distance, 4) AS closest,",
            "           crosses_folder",
            "    FROM `{PROJECT}.drive_insights.file_bridges`",
            "    ORDER BY crosses_folder DESC, link_count DESC",
            "    LIMIT 25",
            "''').to_dataframe()",
        ),
        markdown(
            "### Relationships that exist in no single file",
            "",
            "Entity pairs that never share a passage, but sit at either end of links between"
            " different files. This is the crossing-the-crossings output.",
        ),
        code(
            "client.query(f'''",
            "    SELECT entity_a, entity_b, type_a, type_b, bridge_count,",
            "           ROUND(closest_distance, 4) AS closest",
            "    FROM `{PROJECT}.drive_insights.indirect_relations`",
            "    ORDER BY bridge_count DESC, closest_distance",
            "    LIMIT 30",
            "''').to_dataframe()",
        ),
        markdown(
            "### Who and what recurs",
            "",
            "Entities ranked by how many *distinct files* mention them. Spanning many files"
            " matters more than being repeated inside one.",
        ),
        code(
            "client.query(f'''",
            "    SELECT display_name, entity_type, file_count, mention_count",
            "    FROM `{PROJECT}.drive_graph.entities`",
            "    WHERE entity_type IN ('PERSON', 'ORG', 'CASE_NUMBER')",
            "    ORDER BY file_count DESC, mention_count DESC",
            "    LIMIT 30",
            "''').to_dataframe()",
        ),
        markdown(
            "### A chronology assembled across sources",
            "",
            "Pick an entity from the table above and get every dated appearance of it,"
            " wherever it came from. `date_source` says where each date was found:"
            " `in_text` (a date in the same passage), `filename`, or `file_mtime`.",
        ),
        code(
            "ENTITY = 'probation'   # substring, casefolded",
            "",
            "client.query(f'''",
            "    SELECT event_date, date_source, entity_text, entity_type,",
            "           file_name, source_kind",
            "    FROM `{PROJECT}.drive_insights.entity_timeline`",
            "    WHERE entity_norm LIKE CONCAT('%', LOWER(@e), '%')",
            "    ORDER BY event_date",
            "    LIMIT 100",
            "''', job_config=bigquery.QueryJobConfig(",
            "    query_parameters=[bigquery.ScalarQueryParameter('e', 'STRING', ENTITY)]",
            ")).to_dataframe()",
        ),
        markdown(
            "### Narrated bridges",
            "",
            "Gemini's read on the strongest cross-file matches. It was told to be blunt and"
            " to label most matches `COINCIDENTAL`, so `looks_meaningful = true` is a real"
            " signal rather than flattery. Empty if you skipped `--insight-feed`.",
        ),
        code(
            "client.query(f'''",
            "    SELECT a_name, b_name, looks_meaningful,",
            "           ROUND(distance, 4) AS distance, assessment",
            "    FROM `{PROJECT}.drive_insights.insight_feed`",
            "    ORDER BY looks_meaningful DESC, distance",
            "    LIMIT 25",
            "''').to_dataframe()",
        ),
        markdown(
            "### Coverage gaps",
            "",
            "Entities present in your documents but absent from every spreadsheet, or the"
            " reverse. Either a data gap or a finding — worth seeing either way.",
        ),
        code(
            "client.query(f'''",
            "    SELECT display_name, entity_type, coverage,",
            "           in_documents, in_tables, file_count",
            "    FROM `{PROJECT}.drive_insights.entity_gaps`",
            "    WHERE coverage != 'both' AND file_count >= 2",
            "    ORDER BY file_count DESC",
            "    LIMIT 30",
            "''').to_dataframe()",
        ),
        markdown(
            "### Ask it anything",
            "",
            "Retrieval-augmented answering over the whole Drive: semantic search fetches the"
            " passages, Gemini answers from them and cites the filenames. It is instructed"
            " to say when the corpus does not contain the answer rather than inventing one —"
            " check the `sources` column against the claim regardless.",
        ),
        code(
            "for row in client.query(f'''",
            "    SELECT answer, sources",
            "    FROM `{PROJECT}.drive_insights.ask`(@q, 12)",
            "''', job_config=bigquery.QueryJobConfig(",
            "    query_parameters=[bigquery.ScalarQueryParameter(",
            "        'q', 'STRING',",
            "        'What concerns were raised about the residency, and by whom?')]",
            ")):",
            "    print(row.answer)",
            "    print('\\nsources:', ', '.join(row.sources or []))",
        ),
        markdown(
            "## 12. Keep it alive",
            "",
            "Everything downstream of the vector table is pure SQL, so BigQuery can refresh"
            " it on a timer with no machine of yours involved. `activate` runs all three"
            " passes and then prints the `bq query --schedule` commands to register them.",
            "",
            "The **ingest** step is the one exception — it needs somewhere with Drive"
            " access. Either re-run this notebook when you have added files, or put `load`"
            " on Cloud Run behind Cloud Scheduler for true hands-off operation.",
        ),
        code(
            "!python pipeline.py activate --project $PROJECT --location $LOCATION \\",
            "    --insight-feed",
        ),
        markdown(
            "### Is it current?",
            "",
            "Each stage records a watermark when it runs. `stale` flags anything that has"
            " not run in 48 hours — the difference between a live system and one that"
            " quietly stopped.",
        ),
        code(
            "client.query(f'''",
            "    SELECT stage, last_run, rows_seen, hours_since, stale",
            "    FROM `{PROJECT}.drive_insights.pipeline_health`",
            "    ORDER BY last_run DESC",
            "''').to_dataframe()",
        ),
        markdown(
            "---",
            "",
            "**Note on native Google files.** Sheets, Docs and Slides are not real files on"
            " the mount — Drive represents them as small stub files with no data. The"
            " pipeline recovers their file id from the stub and exports them through the"
            " Drive API. If Colab's credentials lack the Drive scope they are recorded as"
            " `failed` in the manifest with a clear reason, and everything else still loads."
            " Uploaded `.xlsx` files are real files and are unaffected.",
        ),
    ]

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 0,
        "metadata": {
            "colab": {"provenance": [], "toc_visible": True},
            "kernelspec": {"name": "python3", "display_name": "Python 3"},
            "language_info": {"name": "python"},
        },
        "cells": cells,
    }
    NOTEBOOK.write_text(json.dumps(notebook, indent=1))
    size = NOTEBOOK.stat().st_size
    print(f"wrote {NOTEBOOK.name} ({len(cells)} cells, {size:,} bytes)")


if __name__ == "__main__":
    build()
