#!/usr/bin/env python
import pandas as pd
import os

# Define file paths
UPLOAD_DIR = "/home/ubuntu/upload"
OUTPUT_DIR = "/home/ubuntu/work"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "processed_health_report.md")

# Ensure output directory exists
os.makedirs(OUTPUT_DIR, exist_ok=True)

def process_physio_data():
    """Processes physiological_cycles.csv and returns a markdown table."""
    try:
        df = pd.read_csv(os.path.join(UPLOAD_DIR, "physiological_cycles.csv"))
        df_selected = df[[
            "Cycle start time",
            "Recovery score %",
            "Resting heart rate (bpm)",
            "Heart rate variability (ms)",
            "Sleep performance %",
            "Respiratory rate (rpm)",
            "Day Strain"
        ]].copy()
        df_selected.columns = [
            "Date", "Recovery (%)", "RHR (bpm)", "HRV (ms)",
            "Sleep Perf. (%)", "Resp. Rate (rpm)", "Day Strain"
        ]
        df_selected["Date"] = pd.to_datetime(df_selected["Date"]).dt.date
        df_selected = df_selected.sort_values(by="Date", ascending=False)
        return df_selected.to_markdown(index=False)
    except FileNotFoundError:
        return "_Physiological data file not found._"

def process_sleep_data():
    """Processes sleeps.csv and returns a markdown table."""
    try:
        df = pd.read_csv(os.path.join(UPLOAD_DIR, "sleeps.csv"))
        df_selected = df[[
            "Cycle start time", "Sleep onset", "Wake onset", "Asleep duration (min)",
            "In bed duration (min)", "Light sleep duration (min)",
            "Deep (SWS) duration (min)", "REM duration (min)", "Sleep efficiency %"
        ]].copy()
        df_selected.columns = [
            "Date", "Sleep Onset", "Wake Onset", "Asleep (min)", "In Bed (min)",
            "Light (min)", "Deep (min)", "REM (min)", "Efficiency (%)"
        ]
        df_selected["Date"] = pd.to_datetime(df_selected["Date"]).dt.date
        df_selected["Sleep Onset"] = pd.to_datetime(df_selected["Sleep Onset"]).dt.strftime("%H:%M")
        df_selected["Wake Onset"] = pd.to_datetime(df_selected["Wake Onset"]).dt.strftime("%H:%M")
        df_selected = df_selected.sort_values(by="Date", ascending=False)
        return df_selected.to_markdown(index=False)
    except FileNotFoundError:
        return "_Sleep data file not found._"

def main():
    """Main function to generate the report."""
    physio_table = process_physio_data()
    sleep_table = process_sleep_data()

    with open(OUTPUT_FILE, "w") as f:
        f.write("# Processed Health Data Report\n\n")
        f.write("This report was automatically generated by the Health Data Analyst skill. It consolidates the latest raw data into a clean, analyzable format.\n\n")
        f.write("## Physiological Cycles (Daily Summary)\n\n")
        f.write(physio_table)
        f.write("\n\n## Sleep Details\n\n")
        f.write(sleep_table)

    print(f"Processed health report generated at: {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
