#!/usr/bin/env python3
"""
Build a normalized SQL (SQLite) representation of a session-data.json export.

Fixed schema on purpose: two exports from two different sessions should be
diffable and joinable, which only works if every export uses the same tables.

Usage:
    python3 build_sql.py session-data.json --out-dir <export-folder>

Produces:
    <out-dir>/session-export.sql   (portable text dump: schema + INSERTs)
    <out-dir>/session-export.db    (queryable SQLite database)
"""
import argparse
import json
import sqlite3
import sys
from pathlib import Path

SCHEMA = """
CREATE TABLE sessions (
    session_id      TEXT PRIMARY KEY,
    repo            TEXT,
    branch          TEXT,
    pull_request    TEXT,
    user_name       TEXT,
    user_email      TEXT,
    model           TEXT,
    session_started TEXT,
    export_generated TEXT
);

CREATE TABLE turns (
    turn_id             TEXT PRIMARY KEY,
    session_id          TEXT NOT NULL REFERENCES sessions(session_id),
    turn_index          INTEGER NOT NULL,
    speaker_trigger     TEXT,      -- how the turn arrived: user message, webhook, scheduled check-in, etc.
    user_input          TEXT,
    assistant_output    TEXT,
    intent_literal_ask  TEXT,
    intent_true_objective TEXT,
    intent_delta_note   TEXT
);

CREATE TABLE assistant_actions (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    turn_id     TEXT NOT NULL REFERENCES turns(turn_id),
    seq         INTEGER NOT NULL,
    action      TEXT NOT NULL
);

CREATE TABLE analysis_rows (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    turn_id         TEXT NOT NULL REFERENCES turns(turn_id),
    element         TEXT NOT NULL,
    finding         TEXT NOT NULL,
    reconstructed   INTEGER NOT NULL DEFAULT 0   -- 1 if not a verbatim exposed table
);

CREATE TABLE artifacts (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    turn_id     TEXT NOT NULL REFERENCES turns(turn_id),
    kind        TEXT,       -- file | url | commit | pr | published_artifact
    path_or_url TEXT NOT NULL,
    description TEXT
);

CREATE TABLE tool_failures (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    turn_id     TEXT NOT NULL REFERENCES turns(turn_id),
    tool_name   TEXT,
    error       TEXT,
    resolution  TEXT
);
"""


def esc(val):
    if val is None:
        return "NULL"
    if isinstance(val, (int, float)):
        return str(val)
    return "'" + str(val).replace("'", "''") + "'"


def build(data: dict, out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    sql_path = out_dir / "session-export.sql"
    db_path = out_dir / "session-export.db"

    if db_path.exists():
        db_path.unlink()

    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    cur.executescript(SCHEMA)

    lines = ["-- session-export.sql — generated by skills/session-exporter", "", SCHEMA.strip(), ""]

    sess = data["session"]
    cur.execute(
        "INSERT INTO sessions VALUES (?,?,?,?,?,?,?,?,?)",
        (
            sess.get("session_id"), sess.get("repo"), sess.get("branch"),
            sess.get("pull_request"), sess.get("user_name"), sess.get("user_email"),
            sess.get("model"), sess.get("session_started"), sess.get("export_generated"),
        ),
    )
    lines.append(
        "INSERT INTO sessions VALUES ({},{},{},{},{},{},{},{},{});".format(
            *[esc(sess.get(k)) for k in (
                "session_id", "repo", "branch", "pull_request", "user_name",
                "user_email", "model", "session_started", "export_generated",
            )]
        )
    )

    for i, turn in enumerate(data["turns"]):
        tid = turn["turn_id"]
        cur.execute(
            "INSERT INTO turns VALUES (?,?,?,?,?,?,?,?,?)",
            (
                tid, sess.get("session_id"), i, turn.get("speaker_trigger"),
                turn.get("user_input"), turn.get("assistant_output"),
                turn.get("intent_delta", {}).get("literal_ask"),
                turn.get("intent_delta", {}).get("true_objective"),
                turn.get("intent_delta", {}).get("note"),
            ),
        )
        lines.append(
            "INSERT INTO turns VALUES ({},{},{},{},{},{},{},{},{});".format(
                esc(tid), esc(sess.get("session_id")), esc(i), esc(turn.get("speaker_trigger")),
                esc(turn.get("user_input")), esc(turn.get("assistant_output")),
                esc(turn.get("intent_delta", {}).get("literal_ask")),
                esc(turn.get("intent_delta", {}).get("true_objective")),
                esc(turn.get("intent_delta", {}).get("note")),
            )
        )

        for seq, action in enumerate(turn.get("assistant_actions", [])):
            cur.execute("INSERT INTO assistant_actions (turn_id, seq, action) VALUES (?,?,?)", (tid, seq, action))
            lines.append(f"INSERT INTO assistant_actions (turn_id, seq, action) VALUES ({esc(tid)},{esc(seq)},{esc(action)});")

        for row in turn.get("supporting_analysis", []):
            recon = 1 if row.get("reconstructed") else 0
            cur.execute(
                "INSERT INTO analysis_rows (turn_id, element, finding, reconstructed) VALUES (?,?,?,?)",
                (tid, row["element"], row["finding"], recon),
            )
            lines.append(
                f"INSERT INTO analysis_rows (turn_id, element, finding, reconstructed) VALUES "
                f"({esc(tid)},{esc(row['element'])},{esc(row['finding'])},{recon});"
            )

        for art in turn.get("artifacts_produced", []):
            cur.execute(
                "INSERT INTO artifacts (turn_id, kind, path_or_url, description) VALUES (?,?,?,?)",
                (tid, art.get("kind"), art["path_or_url"], art.get("description")),
            )
            lines.append(
                f"INSERT INTO artifacts (turn_id, kind, path_or_url, description) VALUES "
                f"({esc(tid)},{esc(art.get('kind'))},{esc(art['path_or_url'])},{esc(art.get('description'))});"
            )

        for fail in turn.get("tool_failures", []):
            cur.execute(
                "INSERT INTO tool_failures (turn_id, tool_name, error, resolution) VALUES (?,?,?,?)",
                (tid, fail.get("tool_name"), fail.get("error"), fail.get("resolution")),
            )
            lines.append(
                f"INSERT INTO tool_failures (turn_id, tool_name, error, resolution) VALUES "
                f"({esc(tid)},{esc(fail.get('tool_name'))},{esc(fail.get('error'))},{esc(fail.get('resolution'))});"
            )

    conn.commit()
    conn.close()
    sql_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {sql_path} and {db_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("session_json")
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()
    data = json.loads(Path(args.session_json).read_text())
    build(data, Path(args.out_dir))


if __name__ == "__main__":
    sys.exit(main())
